
INSERT INTO ENTIDADE_MODELO_RELACIONADA(descricao_relacao) VALUES ('Descrição smiles relação 1');
INSERT INTO ENTIDADE_MODELO_RELACIONADA(descricao_relacao) VALUES ('Descrição smiles relação 2');


INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descrição smiles 1', 1);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descrição smiles 2', 1);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descrição smiles 3', 1);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descrição smiles 4', 2);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descrição smiles 5', 2);