
INSERT INTO ENTIDADE_MODELO_RELACIONADA(descricao_relacao) VALUES ('Descricao smiles relacao 1');
INSERT INTO ENTIDADE_MODELO_RELACIONADA(descricao_relacao) VALUES ('Descricao smiles relacao 2');


INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 1', 1);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 2', 1);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 3', 1);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 4', 2);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 5', 2);