
INSERT INTO ENTIDADE_MODELO_RELACIONADA(descricao_relacao) VALUES ('Descricao smiles relacao 1');
INSERT INTO ENTIDADE_MODELO_RELACIONADA(descricao_relacao) VALUES ('Descricao smiles relacao 2');

INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 1', 1);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 2', 1);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 3', 1);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 4', 2);
INSERT INTO ENTIDADE_MODELO(DESCRICAO, ENTIDADE_MODELO_RELACIONADA_ID) VALUES ('Descricao smiles 5', 2);

INSERT INTO USUARIO_ENTITY(NOME, CODIGO_SMILES) VALUES ('Aquila', '1234560001');
INSERT INTO USUARIO_ENTITY(NOME, CODIGO_SMILES) VALUES ('Lucas',  '1234560002');
INSERT INTO USUARIO_ENTITY(NOME, CODIGO_SMILES) VALUES ('Marcus', '1234560003');

INSERT INTO WISH_LIST_ENTITY(DESCRICAO, USUARIO_ENTITY_ID, DATA_IDA, DATA_VOLTA, LOCAL_ORIGEM, LOCAL_DESTINO,COTACAO_ATUAL ) VALUES ('Aniversario', 3, '2021-05-01', '2021-06-01', 'POA', 'REC', 1000.0);
INSERT INTO WISH_LIST_ENTITY(DESCRICAO, USUARIO_ENTITY_ID, DATA_IDA, DATA_VOLTA, LOCAL_ORIGEM, LOCAL_DESTINO,COTACAO_ATUAL ) VALUES ('Natal', 3, '2021-12-01', '2021-12-30', 'POA', 'REC', 1000.0);
INSERT INTO WISH_LIST_ENTITY(DESCRICAO, USUARIO_ENTITY_ID, DATA_IDA, DATA_VOLTA, LOCAL_ORIGEM, LOCAL_DESTINO,COTACAO_ATUAL ) VALUES ('Ferias', 3, '2022-01-01', '2022-02-20', 'POA', 'REC', 1000.0);